// source: sketches.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

let jspb = require('google-protobuf');

let goog = jspb;
let global = Function('return this')();

goog.exportSymbol('proto.SketchesProto', null, global);
goog.exportSymbol('proto.SketchesProto.Average', null, global);
goog.exportSymbol('proto.SketchesProto.Boundary', null, global);
goog.exportSymbol('proto.SketchesProto.Maximum', null, global);
goog.exportSymbol('proto.SketchesProto.Original', null, global);
goog.exportSymbol('proto.SketchesProto.OriginalData', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SketchesProto = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SketchesProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
   * @public
   * @override
   */
    proto.SketchesProto.displayName = 'proto.SketchesProto';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SketchesProto.Average = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, proto.SketchesProto.Average.repeatedFields_, null);
};
goog.inherits(proto.SketchesProto.Average, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
   * @public
   * @override
   */
    proto.SketchesProto.Average.displayName = 'proto.SketchesProto.Average';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SketchesProto.Maximum = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, proto.SketchesProto.Maximum.repeatedFields_, null);
};
goog.inherits(proto.SketchesProto.Maximum, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
   * @public
   * @override
   */
    proto.SketchesProto.Maximum.displayName = 'proto.SketchesProto.Maximum';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SketchesProto.Boundary = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, proto.SketchesProto.Boundary.repeatedFields_, null);
};
goog.inherits(proto.SketchesProto.Boundary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
   * @public
   * @override
   */
    proto.SketchesProto.Boundary.displayName = 'proto.SketchesProto.Boundary';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SketchesProto.Original = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, proto.SketchesProto.Original.repeatedFields_, null);
};
goog.inherits(proto.SketchesProto.Original, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
   * @public
   * @override
   */
    proto.SketchesProto.Original.displayName = 'proto.SketchesProto.Original';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SketchesProto.OriginalData = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, proto.SketchesProto.OriginalData.repeatedFields_, null);
};
goog.inherits(proto.SketchesProto.OriginalData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
   * @public
   * @override
   */
    proto.SketchesProto.OriginalData.displayName = 'proto.SketchesProto.OriginalData';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
    proto.SketchesProto.prototype.toObject = function (opt_includeInstance) {
        return proto.SketchesProto.toObject(opt_includeInstance, this);
    };


    /**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SketchesProto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
    proto.SketchesProto.toObject = function (includeInstance, msg) {
        let f; let
            obj = {
                max: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
                min: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
                starttime: jspb.Message.getFieldWithDefault(msg, 3, 0),
                frequency: jspb.Message.getFieldWithDefault(msg, 4, 0),
                average: (f = msg.getAverage()) && proto.SketchesProto.Average.toObject(includeInstance, f),
                maximum: (f = msg.getMaximum()) && proto.SketchesProto.Maximum.toObject(includeInstance, f),
                boundary: (f = msg.getBoundary()) && proto.SketchesProto.Boundary.toObject(includeInstance, f),
                original: (f = msg.getOriginal()) && proto.SketchesProto.Original.toObject(includeInstance, f),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SketchesProto}
 */
proto.SketchesProto.deserializeBinary = function (bytes) {
    let reader = new jspb.BinaryReader(bytes);
    let msg = new proto.SketchesProto();
    return proto.SketchesProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SketchesProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SketchesProto}
 */
proto.SketchesProto.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        let field = reader.getFieldNumber();
        switch (field) {
        case 1:
            var value = /** @type {number} */ (reader.readDouble());
            msg.setMax(value);
            break;
        case 2:
            var value = /** @type {number} */ (reader.readDouble());
            msg.setMin(value);
            break;
        case 3:
            var value = /** @type {number} */ (reader.readInt64());
            msg.setStarttime(value);
            break;
        case 4:
            var value = /** @type {number} */ (reader.readInt32());
            msg.setFrequency(value);
            break;
        case 5:
            var value = new proto.SketchesProto.Average();
            reader.readMessage(value, proto.SketchesProto.Average.deserializeBinaryFromReader);
            msg.setAverage(value);
            break;
        case 6:
            var value = new proto.SketchesProto.Maximum();
            reader.readMessage(value, proto.SketchesProto.Maximum.deserializeBinaryFromReader);
            msg.setMaximum(value);
            break;
        case 7:
            var value = new proto.SketchesProto.Boundary();
            reader.readMessage(value, proto.SketchesProto.Boundary.deserializeBinaryFromReader);
            msg.setBoundary(value);
            break;
        case 8:
            var value = new proto.SketchesProto.Original();
            reader.readMessage(value, proto.SketchesProto.Original.deserializeBinaryFromReader);
            msg.setOriginal(value);
            break;
        default:
            reader.skipField();
            break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SketchesProto.prototype.serializeBinary = function () {
    let writer = new jspb.BinaryWriter();
    proto.SketchesProto.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SketchesProto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SketchesProto.serializeBinaryToWriter = function (message, writer) {
    let f;
    f = message.getMax();
    if (f !== 0.0) {
        writer.writeDouble(
            1,
            f,
        );
    }
    f = message.getMin();
    if (f !== 0.0) {
        writer.writeDouble(
            2,
            f,
        );
    }
    f = message.getStarttime();
    if (f !== 0) {
        writer.writeInt64(
            3,
            f,
        );
    }
    f = message.getFrequency();
    if (f !== 0) {
        writer.writeInt32(
            4,
            f,
        );
    }
    f = message.getAverage();
    if (f != null) {
        writer.writeMessage(
            5,
            f,
            proto.SketchesProto.Average.serializeBinaryToWriter,
        );
    }
    f = message.getMaximum();
    if (f != null) {
        writer.writeMessage(
            6,
            f,
            proto.SketchesProto.Maximum.serializeBinaryToWriter,
        );
    }
    f = message.getBoundary();
    if (f != null) {
        writer.writeMessage(
            7,
            f,
            proto.SketchesProto.Boundary.serializeBinaryToWriter,
        );
    }
    f = message.getOriginal();
    if (f != null) {
        writer.writeMessage(
            8,
            f,
            proto.SketchesProto.Original.serializeBinaryToWriter,
        );
    }
};


/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SketchesProto.Average.repeatedFields_ = [1, 2];


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
    proto.SketchesProto.Average.prototype.toObject = function (opt_includeInstance) {
        return proto.SketchesProto.Average.toObject(opt_includeInstance, this);
    };


    /**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SketchesProto.Average} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
    proto.SketchesProto.Average.toObject = function (includeInstance, msg) {
        let f; let
            obj = {
                topdataList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f,
                bottomdataList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 2)) == null ? undefined : f,
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SketchesProto.Average}
 */
proto.SketchesProto.Average.deserializeBinary = function (bytes) {
    let reader = new jspb.BinaryReader(bytes);
    let msg = new proto.SketchesProto.Average();
    return proto.SketchesProto.Average.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SketchesProto.Average} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SketchesProto.Average}
 */
proto.SketchesProto.Average.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        let field = reader.getFieldNumber();
        switch (field) {
        case 1:
            var value = /** @type {!Array<number>} */ (reader.readPackedDouble());
            msg.setTopdataList(value);
            break;
        case 2:
            var value = /** @type {!Array<number>} */ (reader.readPackedDouble());
            msg.setBottomdataList(value);
            break;
        default:
            reader.skipField();
            break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SketchesProto.Average.prototype.serializeBinary = function () {
    let writer = new jspb.BinaryWriter();
    proto.SketchesProto.Average.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SketchesProto.Average} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SketchesProto.Average.serializeBinaryToWriter = function (message, writer) {
    let f;
    f = message.getTopdataList();
    if (f.length > 0) {
        writer.writePackedDouble(
            1,
            f,
        );
    }
    f = message.getBottomdataList();
    if (f.length > 0) {
        writer.writePackedDouble(
            2,
            f,
        );
    }
};


/**
 * repeated double topData = 1;
 * @return {!Array<number>}
 */
proto.SketchesProto.Average.prototype.getTopdataList = function () {
    return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/** @param {!Array<number>} value */
proto.SketchesProto.Average.prototype.setTopdataList = function (value) {
    jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.SketchesProto.Average.prototype.addTopdata = function (value, opt_index) {
    jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.SketchesProto.Average.prototype.clearTopdataList = function () {
    this.setTopdataList([]);
};


/**
 * repeated double bottomData = 2;
 * @return {!Array<number>}
 */
proto.SketchesProto.Average.prototype.getBottomdataList = function () {
    return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/** @param {!Array<number>} value */
proto.SketchesProto.Average.prototype.setBottomdataList = function (value) {
    jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.SketchesProto.Average.prototype.addBottomdata = function (value, opt_index) {
    jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.SketchesProto.Average.prototype.clearBottomdataList = function () {
    this.setBottomdataList([]);
};


/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SketchesProto.Maximum.repeatedFields_ = [1];


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
    proto.SketchesProto.Maximum.prototype.toObject = function (opt_includeInstance) {
        return proto.SketchesProto.Maximum.toObject(opt_includeInstance, this);
    };


    /**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SketchesProto.Maximum} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
    proto.SketchesProto.Maximum.toObject = function (includeInstance, msg) {
        let f; let
            obj = {
                dataList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f,
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SketchesProto.Maximum}
 */
proto.SketchesProto.Maximum.deserializeBinary = function (bytes) {
    let reader = new jspb.BinaryReader(bytes);
    let msg = new proto.SketchesProto.Maximum();
    return proto.SketchesProto.Maximum.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SketchesProto.Maximum} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SketchesProto.Maximum}
 */
proto.SketchesProto.Maximum.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        let field = reader.getFieldNumber();
        switch (field) {
        case 1:
            var value = /** @type {!Array<number>} */ (reader.readPackedDouble());
            msg.setDataList(value);
            break;
        default:
            reader.skipField();
            break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SketchesProto.Maximum.prototype.serializeBinary = function () {
    let writer = new jspb.BinaryWriter();
    proto.SketchesProto.Maximum.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SketchesProto.Maximum} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SketchesProto.Maximum.serializeBinaryToWriter = function (message, writer) {
    let f;
    f = message.getDataList();
    if (f.length > 0) {
        writer.writePackedDouble(
            1,
            f,
        );
    }
};


/**
 * repeated double data = 1;
 * @return {!Array<number>}
 */
proto.SketchesProto.Maximum.prototype.getDataList = function () {
    return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/** @param {!Array<number>} value */
proto.SketchesProto.Maximum.prototype.setDataList = function (value) {
    jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.SketchesProto.Maximum.prototype.addData = function (value, opt_index) {
    jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.SketchesProto.Maximum.prototype.clearDataList = function () {
    this.setDataList([]);
};


/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SketchesProto.Boundary.repeatedFields_ = [1, 2];


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
    proto.SketchesProto.Boundary.prototype.toObject = function (opt_includeInstance) {
        return proto.SketchesProto.Boundary.toObject(opt_includeInstance, this);
    };


    /**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SketchesProto.Boundary} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
    proto.SketchesProto.Boundary.toObject = function (includeInstance, msg) {
        let f; let
            obj = {
                topdataList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f,
                bottomdataList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 2)) == null ? undefined : f,
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SketchesProto.Boundary}
 */
proto.SketchesProto.Boundary.deserializeBinary = function (bytes) {
    let reader = new jspb.BinaryReader(bytes);
    let msg = new proto.SketchesProto.Boundary();
    return proto.SketchesProto.Boundary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SketchesProto.Boundary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SketchesProto.Boundary}
 */
proto.SketchesProto.Boundary.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        let field = reader.getFieldNumber();
        switch (field) {
        case 1:
            var value = /** @type {!Array<number>} */ (reader.readPackedDouble());
            msg.setTopdataList(value);
            break;
        case 2:
            var value = /** @type {!Array<number>} */ (reader.readPackedDouble());
            msg.setBottomdataList(value);
            break;
        default:
            reader.skipField();
            break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SketchesProto.Boundary.prototype.serializeBinary = function () {
    let writer = new jspb.BinaryWriter();
    proto.SketchesProto.Boundary.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SketchesProto.Boundary} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SketchesProto.Boundary.serializeBinaryToWriter = function (message, writer) {
    let f;
    f = message.getTopdataList();
    if (f.length > 0) {
        writer.writePackedDouble(
            1,
            f,
        );
    }
    f = message.getBottomdataList();
    if (f.length > 0) {
        writer.writePackedDouble(
            2,
            f,
        );
    }
};


/**
 * repeated double topData = 1;
 * @return {!Array<number>}
 */
proto.SketchesProto.Boundary.prototype.getTopdataList = function () {
    return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/** @param {!Array<number>} value */
proto.SketchesProto.Boundary.prototype.setTopdataList = function (value) {
    jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.SketchesProto.Boundary.prototype.addTopdata = function (value, opt_index) {
    jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.SketchesProto.Boundary.prototype.clearTopdataList = function () {
    this.setTopdataList([]);
};


/**
 * repeated double bottomData = 2;
 * @return {!Array<number>}
 */
proto.SketchesProto.Boundary.prototype.getBottomdataList = function () {
    return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/** @param {!Array<number>} value */
proto.SketchesProto.Boundary.prototype.setBottomdataList = function (value) {
    jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.SketchesProto.Boundary.prototype.addBottomdata = function (value, opt_index) {
    jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.SketchesProto.Boundary.prototype.clearBottomdataList = function () {
    this.setBottomdataList([]);
};


/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SketchesProto.Original.repeatedFields_ = [1];


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
    proto.SketchesProto.Original.prototype.toObject = function (opt_includeInstance) {
        return proto.SketchesProto.Original.toObject(opt_includeInstance, this);
    };


    /**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SketchesProto.Original} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
    proto.SketchesProto.Original.toObject = function (includeInstance, msg) {
        let f; let
            obj = {
                dataList: jspb.Message.toObjectList(msg.getDataList(),
                    proto.SketchesProto.OriginalData.toObject, includeInstance),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SketchesProto.Original}
 */
proto.SketchesProto.Original.deserializeBinary = function (bytes) {
    let reader = new jspb.BinaryReader(bytes);
    let msg = new proto.SketchesProto.Original();
    return proto.SketchesProto.Original.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SketchesProto.Original} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SketchesProto.Original}
 */
proto.SketchesProto.Original.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        let field = reader.getFieldNumber();
        switch (field) {
        case 1:
            var value = new proto.SketchesProto.OriginalData();
            reader.readMessage(value, proto.SketchesProto.OriginalData.deserializeBinaryFromReader);
            msg.addData(value);
            break;
        default:
            reader.skipField();
            break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SketchesProto.Original.prototype.serializeBinary = function () {
    let writer = new jspb.BinaryWriter();
    proto.SketchesProto.Original.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SketchesProto.Original} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SketchesProto.Original.serializeBinaryToWriter = function (message, writer) {
    let f;
    f = message.getDataList();
    if (f.length > 0) {
        writer.writeRepeatedMessage(
            1,
            f,
            proto.SketchesProto.OriginalData.serializeBinaryToWriter,
        );
    }
};


/**
 * repeated OriginalData data = 1;
 * @return {!Array<!proto.SketchesProto.OriginalData>}
 */
proto.SketchesProto.Original.prototype.getDataList = function () {
    return /** @type{!Array<!proto.SketchesProto.OriginalData>} */ (
        jspb.Message.getRepeatedWrapperField(this, proto.SketchesProto.OriginalData, 1));
};


/** @param {!Array<!proto.SketchesProto.OriginalData>} value */
proto.SketchesProto.Original.prototype.setDataList = function (value) {
    jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.SketchesProto.OriginalData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SketchesProto.OriginalData}
 */
proto.SketchesProto.Original.prototype.addData = function (opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.SketchesProto.OriginalData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.SketchesProto.Original.prototype.clearDataList = function () {
    this.setDataList([]);
};


/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SketchesProto.OriginalData.repeatedFields_ = [1];


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
    proto.SketchesProto.OriginalData.prototype.toObject = function (opt_includeInstance) {
        return proto.SketchesProto.OriginalData.toObject(opt_includeInstance, this);
    };


    /**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SketchesProto.OriginalData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
    proto.SketchesProto.OriginalData.toObject = function (includeInstance, msg) {
        let f; let
            obj = {
                dataList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f,
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SketchesProto.OriginalData}
 */
proto.SketchesProto.OriginalData.deserializeBinary = function (bytes) {
    let reader = new jspb.BinaryReader(bytes);
    let msg = new proto.SketchesProto.OriginalData();
    return proto.SketchesProto.OriginalData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SketchesProto.OriginalData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SketchesProto.OriginalData}
 */
proto.SketchesProto.OriginalData.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        let field = reader.getFieldNumber();
        switch (field) {
        case 1:
            var value = /** @type {!Array<number>} */ (reader.readPackedDouble());
            msg.setDataList(value);
            break;
        default:
            reader.skipField();
            break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SketchesProto.OriginalData.prototype.serializeBinary = function () {
    let writer = new jspb.BinaryWriter();
    proto.SketchesProto.OriginalData.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SketchesProto.OriginalData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SketchesProto.OriginalData.serializeBinaryToWriter = function (message, writer) {
    let f;
    f = message.getDataList();
    if (f.length > 0) {
        writer.writePackedDouble(
            1,
            f,
        );
    }
};


/**
 * repeated double data = 1;
 * @return {!Array<number>}
 */
proto.SketchesProto.OriginalData.prototype.getDataList = function () {
    return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/** @param {!Array<number>} value */
proto.SketchesProto.OriginalData.prototype.setDataList = function (value) {
    jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.SketchesProto.OriginalData.prototype.addData = function (value, opt_index) {
    jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.SketchesProto.OriginalData.prototype.clearDataList = function () {
    this.setDataList([]);
};


/**
 * optional double max = 1;
 * @return {number}
 */
proto.SketchesProto.prototype.getMax = function () {
    return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/** @param {number} value */
proto.SketchesProto.prototype.setMax = function (value) {
    jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double min = 2;
 * @return {number}
 */
proto.SketchesProto.prototype.getMin = function () {
    return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.SketchesProto.prototype.setMin = function (value) {
    jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional int64 startTime = 3;
 * @return {number}
 */
proto.SketchesProto.prototype.getStarttime = function () {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.SketchesProto.prototype.setStarttime = function (value) {
    jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 frequency = 4;
 * @return {number}
 */
proto.SketchesProto.prototype.getFrequency = function () {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.SketchesProto.prototype.setFrequency = function (value) {
    jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional Average average = 5;
 * @return {?proto.SketchesProto.Average}
 */
proto.SketchesProto.prototype.getAverage = function () {
    return /** @type{?proto.SketchesProto.Average} */ (
        jspb.Message.getWrapperField(this, proto.SketchesProto.Average, 5));
};


/** @param {?proto.SketchesProto.Average|undefined} value */
proto.SketchesProto.prototype.setAverage = function (value) {
    jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.SketchesProto.prototype.clearAverage = function () {
    this.setAverage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SketchesProto.prototype.hasAverage = function () {
    return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Maximum maximum = 6;
 * @return {?proto.SketchesProto.Maximum}
 */
proto.SketchesProto.prototype.getMaximum = function () {
    return /** @type{?proto.SketchesProto.Maximum} */ (
        jspb.Message.getWrapperField(this, proto.SketchesProto.Maximum, 6));
};


/** @param {?proto.SketchesProto.Maximum|undefined} value */
proto.SketchesProto.prototype.setMaximum = function (value) {
    jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.SketchesProto.prototype.clearMaximum = function () {
    this.setMaximum(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SketchesProto.prototype.hasMaximum = function () {
    return jspb.Message.getField(this, 6) != null;
};


/**
 * optional Boundary boundary = 7;
 * @return {?proto.SketchesProto.Boundary}
 */
proto.SketchesProto.prototype.getBoundary = function () {
    return /** @type{?proto.SketchesProto.Boundary} */ (
        jspb.Message.getWrapperField(this, proto.SketchesProto.Boundary, 7));
};


/** @param {?proto.SketchesProto.Boundary|undefined} value */
proto.SketchesProto.prototype.setBoundary = function (value) {
    jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.SketchesProto.prototype.clearBoundary = function () {
    this.setBoundary(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SketchesProto.prototype.hasBoundary = function () {
    return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Original original = 8;
 * @return {?proto.SketchesProto.Original}
 */
proto.SketchesProto.prototype.getOriginal = function () {
    return /** @type{?proto.SketchesProto.Original} */ (
        jspb.Message.getWrapperField(this, proto.SketchesProto.Original, 8));
};


/** @param {?proto.SketchesProto.Original|undefined} value */
proto.SketchesProto.prototype.setOriginal = function (value) {
    jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.SketchesProto.prototype.clearOriginal = function () {
    this.setOriginal(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SketchesProto.prototype.hasOriginal = function () {
    return jspb.Message.getField(this, 8) != null;
};


goog.object.extend(exports, proto);
